packages:
  - desktop
  - apps/*
  - packages/*
  - themes/*
  - plugins/*

allowBuilds:
  '@owdproject/nx': true
onlyBuiltDependencies:
  - '@owdproject/nx'
  - '@owdproject/theme-nova'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
  - unrs-resolver
