// Generated by @owdproject/module-docs — do not edit
import { defineContentConfig, defineCollection } from '@nuxt/content'

export default defineContentConfig({
  collections: {
  "owd_docs": defineCollection({
    type: 'page',
    source: {
      cwd: "/home/dxlliv/Development/Projects/OWD/client/packages/module-docs/content",
      include: "docs/**",
      prefix: "/docs",
      
    },
  }),
  "owd_docs_project": defineCollection({
    type: 'page',
    source: {
      cwd: "/home/dxlliv/Development/Projects/OWD/client/packages/module-docs/content",
      include: "docs/**",
      prefix: "/docs",
      
    },
  }),
  },
})
