import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Nuxt } from '@nuxt/schema'
import {
  collectionNameForSource,
  getOwdDocsSources,
} from '../registerOwdDocsSource'

export function writeOwdContentConfig(nuxt: Nuxt, basePath: string) {
  const sources = getOwdDocsSources(nuxt)
  if (sources.length === 0) return

  const collectionEntries = sources
    .map((source) => {
      const name =
        source.id === 'core' ? 'owd_docs' : collectionNameForSource(source.id)
      const cwd = source.cwd.replace(/\\/g, '/')
      const include = source.include ?? '**/*.md'
      const prefix = source.prefix ?? basePath
      const exclude = source.exclude?.length
        ? `exclude: ${JSON.stringify(source.exclude)},`
        : ''

      return `  ${JSON.stringify(name)}: defineCollection({
    type: 'page',
    source: {
      cwd: ${JSON.stringify(cwd)},
      include: ${JSON.stringify(include)},
      prefix: ${JSON.stringify(prefix)},
      ${exclude}
    },
  }),`
    })
    .join('\n')

  const contents = `// Generated by @owdproject/module-docs — do not edit
import { defineContentConfig, defineCollection } from '@nuxt/content'

export default defineContentConfig({
  collections: {
${collectionEntries}
  },
})
`

  const path = join(nuxt.options.rootDir, 'content.config.ts')
  writeFileSync(path, contents, 'utf8')
}
